AbcJobSite.MVC/Controllers/ApplicantController.cs
using AbcJobsite.Services;
using AbcJobSite.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbcJobSite.MVC.Controllers
{
    [Authorize]
    public class ApplicantController : Controller
    {

     
        private ApplicantService CreateApplicantServices()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ApplicantService(userId);
            return service;
        }
        // GET: Applicant 
        public ActionResult Index()
        {
            var service = CreateApplicantServices();

            var model = service.GetApplicants();
            return View(model);
        }
        //Get: Applicant/Create
        public ActionResult Create()

        {
            return View();
        }

        //Post: /Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ApplicantCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateApplicantServices();
            if (service.CreateApplicant(model))
            {
                TempData["SaveResult"] = "Applicant created successfully";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Applicant could not be created");
            return View(model);
        }


        public ActionResult Details(int id)
        {
            var svc = CreateApplicantServices();
            var model = svc.GetApplicantById(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var service = CreateApplicantServices();
            var detail = service.GetApplicantById(id);
            var model =
                new ApplicantEdit
                {
                    Id = detail.Id,
                    ApplicantName = detail.ApplicantName,
                    ApplicantEmail = detail.ApplicantEmail,
                    PhoneNumber = detail.PhoneNumber,
                    Location = detail.Location,
                    Address = detail.Address,
                    CreatedUtc = detail.CreatedUtc
                 
                };
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(int id, ApplicantEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateApplicantServices();
            if (service.UpdateApplicant(model))
            {
                TempData["SaveResult"] = "Applicant was updated successfully.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Applicant could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateApplicantServices();
            var model = svc.GetApplicantById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateApplicantServices();
            service.DeleteApplicant(id);
            TempData["SaveResult"] = "Applicant was delected";
            return RedirectToAction("Index");
        }
    }
}

AbcJobSite.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbcJobSite.MVC.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
        

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
       

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AbcJobSite.MVC/Controllers/JobController.cs
using AbcJobsite.Services;
using AbcJobSite.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbcJobSite.MVC.Controllers
{
   

    public class JobController : Controller
    {
        private JobService CreateJobServices()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new JobService(userId);
            return service;
        }
        // GET: Job
        public ActionResult Index()
        {
            var service = CreateJobServices();

            var model = service.GetJobs();
            return View(model.ToList());
        }
        //Get: Job/Create
        public ActionResult Create()

        {
            return View();
        }
        //Post: Job/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateJobServices();
            if (service.CreateJob(model))
            {
                TempData["SaveResult"] = "Employer created successfully";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Employer could not be created");
            return View(model);
        }




        public ActionResult Details(int id)
        {
            var svc = CreateJobServices();
            var model = svc.GetJobById(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var service = CreateJobServices();
            var detail = service.GetJobById(id);
            var model =
                new JobEdit
                {
                    Id = detail.Id,
                    JobTitle = detail.JobTitle,
                    JobDescription = detail.JobDescription,
                    Location =detail.Location
                    
                };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, JobEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateJobServices();
            if (service.UpdateJob(model))
            {
                TempData["SaveResult"] = "Job was updated successfully.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Job could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateJobServices();
            var model = svc.GetJobById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateJobServices();
            service.DeleteJob(id);
            TempData["SaveResult"] = "Job was delected successfully";
            return RedirectToAction("Index");
        }
    }

}

AbcJobSite.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    ABOUT US
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pretium nibh eros, vel venenatis metus fringilla feugiat. Ut molestie ornare nulla. Duis semper justo arcu, eu varius velit cursus in. Cras eget facilisis felis. Duis volutpat neque erat, non commodo nisi lacinia non. Donec posuere augue lacus, et aliquam nibh iaculis id. Nulla vestibulum interdum libero luctus tristique.

    Ut venenatis iaculis suscipit. Vestibulum sed nunc at sem sollicitudin iaculis. Nullam arcu nunc, vulputate vitae accumsan venenatis, condimentum ac ex. Integer turpis purus, sollicitudin ac commodo vitae, luctus pretium dui. Suspendisse gravida lacus eget feugiat molestie. Nam suscipit sapien eget tellus ultricies feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan vel nulla sit amet suscipit. Sed egestas dolor ac consectetur pretium. Nulla sed tempus augue, et vulputate mi. Vestibulum efficitur tellus vel feugiat mattis. Cras vel tristique dui. Quisque sit amet mollis risus.

    Nulla facilisi. Curabitur consectetur mi sit amet tellus pulvinar, et vestibulum est eleifend. Praesent ut odio et libero malesuada malesuada. Aenean a neque malesuada, lobortis tortor vel, sagittis ipsum. Nulla rutrum viverra elit, ultrices tempus libero rutrum id. Aenean congue aliquet mi sed finibus. Sed eu velit bibendum, efficitur lectus elementum, scelerisque ex. Integer vitae consectetur lorem. Sed mauris ligula, tristique vitae nunc nec, mattis fermentum erat. Vestibulum vel mi faucibus, ullamcorper ante nec, dictum purus. Ut iaculis vulputate massa, vitae convallis mi tempor id. Donec fringilla purus eget neque feugiat dictum. Quisque posuere tortor augue, a auctor mauris gravida pellentesque.

    Maecenas sodales pretium lorem, sed pharetra velit ultrices eu. Sed eu maximus elit. Integer elementum dignissim diam, ut sollicitudin risus dictum quis. Donec ante turpis, elementum eget semper sit amet, hendrerit et arcu. Pellentesque lacinia in mi vel auctor. Pellentesque in rutrum massa. Suspendisse mollis venenatis volutpat. Praesent interdum dapibus dolor eu consectetur. Phasellus tempor enim vitae dui posuere, nec vulputate felis bibendum. Suspendisse gravida ut velit et faucibus. In hac habitasse platea dictumst. Duis vitae est metus.

    Sed gravida enim erat, quis malesuada felis dictum aliquam. Nunc et felis posuere, egestas metus quis, laoreet justo. Cras sagittis erat eget ante cursus, ac congue risus interdum. Donec vel dolor nisi. Aenean augue tellus, imperdiet quis turpis porta, lacinia tristique felis. Mauris id lorem convallis, euismod lacus et, pretium arcu. In hac habitasse platea dictumst. Nullam id neque nec risus sodales consectetur nec nec quam. Suspendisse ultricies leo vel interdum consequat. Maecenas sollicitudin sem odio, ac rhoncus dolor tempus maximus. Nam condimentum sed ante in iaculis. Praesent dignissim condimentum elit, sit amet finibus lacus commodo quis.
</p>

AbcJobSite.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    123 ABCJOBSITE Way<br />
    Indianapolis, IN 46259-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="support@abcjobsite.com">support@abcjobsite.com</a><br />
    <strong>Marketing:</strong> <a href="info@abcjobsite.com">info@abcjobsite.com</a>
</address>

AbcJobSite.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        
        <img src="~/image/pic5.JPG" class="" alt="..." style=width:100% />
        
    </div>
</div>


<body>
    <div class="container">
        <div class="card-group">
            <div class="card">
                <img src="~/image/pic3.JPG" class="card-img-top" alt="..."style= height:85%>
                <div class="card-body">
               

                    <button type="button" class="btn btn-warning"> @Html.ActionLink("Learn more", "About", "Home")</button>
                    
                </div>
            </div>
            <div class="card">
                <img src="~/image/pic2.JPG" class="card-img-top" alt="..." style= height:85% />
               
                <div class="card-body">

                    <button type="button" class="btn btn-warning">@Html.ActionLink("Register Here", "Create", "Applicant")</button>


                </div>
            </div>

            <div class="card">
                <img src="~/image/pic1.JPG" class="card-img-top" alt="..." style= height:85% />
                <div class="card-body">
                  
                    <button type="button" class="btn btn-warning">@Html.ActionLink("Apply", "Index", "Job")</button> 
                </div>
            </div>
        </div>

       
    </div>
</body>