AbcJobSite.MVC/Controllers/JobApplicationController.cs
using AbcJobsite.Services;
using AbcJobSite.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbcJobSite.MVC.Controllers
{
    public class JobApplicationController : Controller
    {
        private JobApplicationService CreateJobApplicationServices()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new JobApplicationService(userId);
            return service;
        }
        // GET: JobApplication
        public ActionResult Index()
        {
            var service = CreateJobApplicationServices();

            var model = service.GetJobApplications();
            return View(model.ToList());
        }
        //Get: JobApplication/Create
        public ActionResult Create()

        {
            return View();
        }

        //Post: JobApplication/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobApplicationCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateJobApplicationServices();
            if (service.CreateJobApplication(model))
            {
                TempData["SaveResult"] = "JobApplication created successfully";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "JobApplication could not be created");
            return View(model);
        }


        public ActionResult Details(int id)
        {
            var svc = CreateJobApplicationServices();
            var model = svc.GetJobApplicationById(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var service = CreateJobApplicationServices();
            var detail = service.GetJobApplicationById(id);
            var model =
                new JobApplicationEdit
                {
                    Id = detail.Id,
                    ApplicantId = detail.ApplicantId,
                   
                    JobId = detail.JobId,
                    DateTimeNow = detail.DateTimeNow
                };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, JobApplicationEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateJobApplicationServices();
            if (service.UpdateJobApplication(model))
            {
                TempData["SaveResult"] = "JobApplication was updated successfully.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "JobApplication could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateJobApplicationServices();
            var model = svc.GetJobApplicationById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateJobApplicationServices();

            service.DeleteJobApplication(id);
            TempData["SaveResult"] = "JobApplication was delected successfully";
            return RedirectToAction("Index");
        }
    }

}

AbcJobSite.MVC/Controllers/JobController.cs
using AbcJobsite.Services;
using AbcJobSite.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbcJobSite.MVC.Controllers
{
   

    public class JobController : Controller
    {
        private JobService CreateJobServices()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new JobService(userId);
            return service;
        }
        // GET: Job
        public ActionResult Index()
        {
            var service = CreateJobServices();

            var model = service.GetJobs();
            return View(model.ToList());
        }
        //Get: Job/Create
        public ActionResult Create()

        {
            return View();
        }
        //Post: Job/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateJobServices();
            if (service.CreateJob(model))
            {
                TempData["SaveResult"] = "Employer created successfully";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Employer could not be created");
            return View(model);
        }




        public ActionResult Details(int id)
        {
            var svc = CreateJobServices();
            var model = svc.GetJobById(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var service = CreateJobServices();
            var detail = service.GetJobById(id);
            var model =
                new JobEdit
                {
                    Id = detail.Id,
                    JobTitle = detail.JobTitle,
                    JobDescription = detail.JobDescription,
                    Location =detail.Location
                    
                };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, JobEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateJobServices();
            if (service.UpdateJob(model))
            {
                TempData["SaveResult"] = "Job was updated successfully.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Job could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateJobServices();
            var model = svc.GetJobById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateJobServices();
            service.DeleteJob(id);
            TempData["SaveResult"] = "Job was delected successfully";
            return RedirectToAction("Index");
        }
    }

}

AbcJobSite.MVC/Views/Job/Create.cshtml
@model AbcJobSite.Model.JobCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>JobCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TypeOfJob, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.TypeOfJob, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TypeOfJob, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployerId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmployerId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmployerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Apply" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <button type="button" class="btn btn-primary">@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbcJobSite.MVC/Views/Job/Delete.cshtml
@model AbcJobSite.Model.JobDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <button type="button" class="btn btn-primary">@Html.ActionLink("Back to List", "Index")
</div>
    }
</div>

AbcJobSite.MVC/Views/Job/Details.cshtml
@model AbcJobSite.Model.JobDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>JobDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

    </dl>
</div>
<div>
    <p>
        <button type="button" class="btn btn-info">@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        <button type="button" class="btn btn-outline-secondary">@Html.ActionLink("Back to List", "Index")
   </p>
</div>

AbcJobSite.MVC/Views/Job/Edit.cshtml
@model AbcJobSite.Model.JobEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobEdit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-success">@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbcJobSite.MVC/Views/Job/Index.cshtml
@model IEnumerable<AbcJobSite.Model.JobList>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <button type="button" class="btn btn-dark">@Html.ActionLink("Create New", "Create")</button> 
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        @ViewBag.SaveResult
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

<table class="table">
    <tr>
        <th>
            <a href="#" class="list-group-item list-group-item-action list-group-item-warning"> @Html.DisplayNameFor(model => model.JobTitle)</a>
           
        </th>
        <th>
            <a href="#" class="list-group-item list-group-item-action list-group-item-success">@Html.DisplayNameFor(model => model.JobDescription)</a>
            
        </th>
        <th>
            <a href="#" class="list-group-item list-group-item-action list-group-item-secondary">@Html.DisplayNameFor(model => model.Location)</a>
            
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div class="card" style="width: 10rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item-warning">@Html.DisplayFor(modelItem => item.JobTitle)</li>
                        
               
                    </ul>
                 
                </div>
                
            </td>
            <td>
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item-success">@Html.DisplayFor(modelItem => item.JobDescription)</li>


                    </ul>

                </div>
                
            </td>
            <td>
                <div class="card" style="width: 10rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item-secondary">@Html.DisplayFor(modelItem => item.Location)</li>


                    </ul>

                </div>
                
            </td>
            <td>
                <button type="button" class="btn btn-info">@Html.ActionLink("Edit", "Edit", new { id = item.Id }) </button>
                <button type="button" class="btn btn-warning">@Html.ActionLink("Details", "Details", new { id = item.Id }) </button>
                <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</button>
                <button type="button" class="btn btn-success">@Html.ActionLink("Apply", "Create", "JobApplication"@*,  new { id = item.Id }, null*@)</button>

                
                
                
            </td>
        </tr>
    }

</table>